steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-docker.pkg.dev/gochen/images/mossy', '.']

images: ['us-docker.pkg.dev/gochen/images/mossy']
options:
  requestedVerifyOption: VERIFIED
  sourceProvenanceHash: ['SHA256']
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
