steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-docker.pkg.dev/gochen/images/gcb-say', '.']

images: ['us-docker.pkg.dev/gochen/images/gcb-say']
options:
  provenance:
    enabled: REQUIRED
    region: GLOBAL
  sourceProvenanceHash: ['SHA256']
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
