steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-docker.pkg.dev/gochen/images/gcb-say', '.']

images: ['us-docker.pkg.dev/gochen/images/gcb-say']
options:
  requestedVerifyOption: VERIFIED
  sourceProvenanceHash: ['SHA256']
