name: 'vm_deploy'

on:
  workflow_dispatch:
    inputs:
      label:
        description: 'The label of the VM image to deploy'
        type: 'string'
        required: true

env:
  PROJECT_ID: 'gochen'
  WIF_PROVIDER: 'projects/220951778751/locations/global/workloadIdentityPools/github-mossy/providers/mossy'
  WIF_SERVICE_ACCOUNT: 'packer@gochen.iam.gserviceaccount.com'
  PROD_REGISTRY: 'prod-vm-images'

concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.ref }}-vm-deploy'
  cancel-in-progress: true

jobs:
  deploy:
      runs-on: 'ubuntu-latest'
      permissions:
        contents: 'read'
        id-token: 'write'
        attestations: 'write'
      env:
        IMAGE_TARBALL_NAME: 'mossy-nginx-${{ inputs.label }}'
      steps:
        - name: 'Checkout'
          uses: 'actions/checkout@v4'

        - name: 'Auth'
          id: 'auth'
          uses: 'google-github-actions/auth@v2'
          with:
            project_id: '${{ env.project_id }}'
            workload_identity_provider: '${{ env.WIF_PROVIDER }}'
            service_account: '${{ env.WIF_SERVICE_ACCOUNT }}'
            token_format: 'access_token'

        - name: 'Set up Cloud SDK'
          uses: 'google-github-actions/setup-gcloud@v2'
          with:
            version: '>= 363.0.0'

        # There is a bug in the documentation!
        # The service account must be able to create Cloud Build builds.
        - name: 'Export temporary image to GCS'
          run: |
            gcloud artifacts generic download \
              --project="${{ env.PROJECT_ID }}" \
              --location="us-central1" \
              --repository="${{ env.PROD_REGISTRY }}" \
              --package="mossy-nginx" \
              --version="${{ inputs.label }}" \
              --name="${{ env.IMAGE_TARBALL_NAME }}.tar.gz"
              --destination="."

            gcloud storage cp "${{ env.IMAGE_TARBALL_NAME }}.tar.gz" "gs://gochen-vms/deploy/${{ env.IMAGE_TARBALL_NAME }}.tar.gz"

        - name: 'Import VM image'
          run: |
            gcloud compute images import \
              --source-file="gs://gochen-vms/deploy/${{ env.IMAGE_TARBALL_NAME }}.tar.gz" \
              "${{ env.IMAGE_TARBALL_NAME }}-prod"

        - name: 'Launch or update VM template'
          run: 'echo "Launch or update VM template"'

        - name: 'Clean up'
          run: |
            gcloud storage rm "gs://gochen-vms/deploy/${{ env.IMAGE_TARBALL_NAME }}.tar.gz"

