name: 'vm_promote'

on:
  workflow_dispatch:
    inputs:
      label:
        description: 'The label of the VM image to promote'
        type: 'string'
        required: true
      suffix:
        description: 'A suffix to differentiate from dev images'
        type: 'string'
        required: false
        default: 'prod'

env:
  PROJECT_ID: 'gochen'
  WIF_PROVIDER: 'projects/220951778751/locations/global/workloadIdentityPools/github-mossy/providers/mossy'
  WIF_SERVICE_ACCOUNT: 'packer@gochen.iam.gserviceaccount.com'
  DEV_REGISTRY: 'dev-vm-images'
  PROD_REGISTRY: 'prod-vm-images'

concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.ref }}-vm-promote'
  cancel-in-progress: true

jobs:
  promote:
      runs-on: 'ubuntu-latest'
      permissions:
        contents: 'read'
        id-token: 'write'
      env:
        IMAGE_TARBALL_NAME: 'mossy-nginx-${{ inputs.label }}'
      steps:
        - name: 'Checkout'
          uses: 'actions/checkout@v4'

        - name: 'Auth'
          id: 'auth'
          uses: 'google-github-actions/auth@v2'
          with:
            project_id: '${{ env.project_id }}'
            workload_identity_provider: '${{ env.WIF_PROVIDER }}'
            service_account: '${{ env.WIF_SERVICE_ACCOUNT }}'
            token_format: 'access_token'

        - name: 'Set up Cloud SDK'
          uses: 'google-github-actions/setup-gcloud@v2'
          with:
            version: '>= 363.0.0'

        - name: 'Verify attestation'
          run: |
            gcloud artifacts generic download \
              --project="${{ env.PROJECT_ID }}" \
              --location="us-central1" \
              --repository="${{ env.DEV_REGISTRY }}" \
              --package="mossy-nginx" \
              --version="${{ inputs.label }}" \
              --destination="artifact"

            cat ./attestation.jsonl

        # There is a bug in the documentation!
        # The service account must be able to create Cloud Build builds.
        - name: 'Export temporary image to GCS'
          run: |
            echo 'Upload VM image...'
            gcloud storage cp "artifact/${{ env.IMAGE_TARBALL_NAME }}.tar.gz" "gs://gochen-vms/deploy/${{ env.IMAGE_TARBALL_NAME }}/"

            echo 'Upload provenance...'
            gcloud storage cp "artifact/attestation.jsonl" "gs://gochen-vms/deploy/${{ env.IMAGE_TARBALL_NAME }}/"

            echo 'Upload faking VSA...'
            echo 'fake' > artifact/vsa.json
            gcloud storage cp "artifact/vsa.json" "gs://gochen-vms/deploy/${{ env.IMAGE_TARBALL_NAME }}/"

        - name: 'Import VM image'
          run: |
            gcloud compute images import \
              --source-file="gs://gochen-vms/deploy/${{ env.IMAGE_TARBALL_NAME }}/${{ env.IMAGE_TARBALL_NAME }}.tar.gz" \
              "${{ env.IMAGE_TARBALL_NAME }}-${{ inputs.suffix }}"

        - name: 'Clean up'
          run: |
            gcloud storage rm "gs://gochen-vms/deploy/${{ env.IMAGE_TARBALL_NAME }}.tar.gz"

        - name: 'Update VM template'
          run: 'echo "Here is when you can update VM template"'
