name: 'vm_promote'

on:
  workflow_dispatch:
    inputs:
      label:
        description: 'The label of the image to promote'
        type: 'string'
        required: true

env:
  PROJECT_ID: 'gochen'
  WIF_PROVIDER: 'projects/220951778751/locations/global/workloadIdentityPools/github-mossy/providers/mossy'
  WIF_SERVICE_ACCOUNT: 'packer@gochen.iam.gserviceaccount.com'
  DEV_REGISTRY: 'dev-vm-images'
  PROD_REGISTRY: 'prod-vm-images'

concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.ref }}-vm-promote'
  cancel-in-progress: true

jobs:
  promote:
      runs-on: 'ubuntu-latest'
      permissions:
        contents: 'read'
        id-token: 'write'
      env:
        IMAGE_TARBALL_NAME: 'mossy-nginx-${{ inputs.label }}'
      steps:
        - name: 'Checkout'
          uses: 'actions/checkout@v4'

        - name: 'Auth'
          id: 'auth'
          uses: 'google-github-actions/auth@v2'
          with:
            project_id: '${{ env.project_id }}'
            workload_identity_provider: '${{ env.WIF_PROVIDER }}'
            service_account: '${{ env.WIF_SERVICE_ACCOUNT }}'
            token_format: 'access_token'

        - name: 'Set up Cloud SDK'
          uses: 'google-github-actions/setup-gcloud@v2'
          with:
            version: '>= 363.0.0'

        - name: 'Verify attestation'
          run: |
            gcloud artifacts generic download \
              --project="${{ env.PROJECT_ID }}" \
              --location="us-central1" \
              --repository="${{ env.DEV_REGISTRY }}" \
              --package="mossy-nginx" \
              --version="${{ inputs.label }}" \
              --name="attestation.jsonl"
              --destination="."

            cat ./attestation.jsonl

        - name: 'Copy artifact'
          run: |
            gcloud artifacts generic download \
              --project="${{ env.PROJECT_ID }}" \
              --location="us-central1" \
              --repository="${{ env.DEV_REGISTRY }}" \
              --package="mossy-nginx" \
              --version="${{ inputs.label }}" \
              --name="${{ env.IMAGE_TARBALL_NAME }}.tar.gz"
              --destination="."

            gcloud artifacts generic upload \
              --project="${{ env.PROJECT_ID }}" \
              --source="${{ env.IMAGE_TARBALL_NAME }}.tar.gz" \
              --package="mossy-nginx" \
              --version="${{ inputs.label }}" \
              --location="us-central1" \
              --repository="${{ env.PROD_REGISTRY }}"

            gcloud artifacts generic upload \
              --project="${{ env.PROJECT_ID }}" \
              --source="attestation.jsonl" \
              --package="mossy-nginx" \
              --version="${{ inputs.label }}" \
              --location="us-central1" \
              --repository="${{ env.PROD_REGISTRY }}"
